displayName: Traefik Cors Plugin
type: middleware

import: github.com/pxxonline/traefik-plugin-cors

summary: 'Traefik Cors Plugin'

testData:
  allowed_methods:
  - "GET"
  - "POST"
  - "PUT"
  allowed_headers:
  - "Origin"
  - "Content-Length"
  - "Content-Type"
  allow_credentials: false